version: '3.6'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_HOST=http://localhost:3001
    ports:
      - 3000:3000

  nginx: # redirects elsewhere
    image: nginx:latest
    ports:
      - 3001:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro